name: rust-ci
on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
